### ISSUE TITLE
Dependency Questions

### ISSUE THREAD

**Issue by jakyote** [JuBan1/notepadqq#10]
Building a package for Arch and ran into a couple discrepancies between expected dependencies according to namcap (arch tool for validating packages) and the dependencies listed in the README, namely:

- Referenced library 'node' is an uninstalled dependency (not mentioned in readme)
- Dependency 'qt5-svg' is included and not required (specified as dependency in readme)

I'm assuming 'node' refers to nodejs and it's needed for the extensions and should be considered optional? Is it required for anything else? (it seems to work fine without it at least)

and i'm guessing 'qt5-svg' was required for the latex style math functionality which i understand has not yet been added to OTE, is it still otherwise required or can it safely be dropped?

**Comment by JuBan1** [comment]
That's about right. Since Nqq's extension support is fairly broken (in this fork and upstream), node is practically useless too.

qt5-svg probably came from the latex extension (which I replaced with OTE's labeling functionality. Unless something silently broke, it works :) so it's not required anymore, but upstream started making use of svgs in other places, so once I get around to rebasing this fork it'll probably become an actual dependency again.

**Comment by jakyote** [comment]
Perfect, this PKGBUILD should be adequate for now then, I'll keep an eye out for when qt5-svg becomes a dependency again. You wouldn't mind if i submit it to the AUR as 'notepadqq-ote-git'? (assuming i can figure it out, it would be my first AUR pkg) I know it's still considered experimental but it seems just as functional as upstream (if not more so, imo).
